version: '3'

services:
  app:
#    image: ipvsix/librespeedtest:latest
    image: ipvsix/dockerlibrespeed:latest
    shm_size: '128mb'
    ports: 
      - 50000:80
    networks:
      - webproxy
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Bangkok
      - TITLE="HTML5 size 5MB 9Jul2022"
      - MODE=standalone
      - TELEMETRY=true
      - ENABLE_ID_OBFUSCATION=true
      - EDACT_IP_ADDRESSES=true
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
      labels:
        - traefik.enable=true
        - traefik.docker.network=webproxy
        - traefik.http.routers.${APPNAME}-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.${APPNAME}-https.entrypoints=websecure
        - traefik.http.routers.${APPNAME}-https.tls.certresolver=default
        - traefik.http.services.${APPNAME}.loadbalancer.server.port=80
networks:
  webproxy:
    external: true